name: "Sanity check"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-stl:
    name: "Build STL"
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4.1.1
      - name: "STL build"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          sudo apt update
          sudo apt install -y openscad
          openscad --version
          for i in *.scad: do
            openscad --export-format binstl -o ${i%.scad}.stl "$i"
          done
          ls -l *.stl

